### ISSUE TITLE
External power source

### ISSUE THREAD

**Issue by lufton** [dala318/esphome-qmi8658#2]
I wonder if you was able to power ESP32-S3 matrix board with external power. I tried to supply 5V directly to 5V pin with my bench power supply. But as soon as I touched 5V and GND pins with probes something strange happend (no smoke, no visible damage), but matrix is not working anymore (just couple the same leds are glowing each time I reboot the board), even with USB C power. I started investigating and found out that there is a `B5819WS` Schottky barrier diod between 5V pin and power from USB C connector, so measering voltage on 5V pin is giving me ~4.6V. Also further down there is `ME6217C33M5G` voltage regulator to power ESP32. According to datasheet it requires 4.3V input, so supplying 5V could potentially burn it, but ESP32 works fine and measuring output voltage gives me 3.3V.
I'm pretty certain I din't reversed poles and diod would also protect the board, but something bad happened. I was going to build custom project based on this board, and I was going to supply power directly, maybe even desolder USB C port, but now I'm not sure how to continue. I have 1 spare board, but afraid I can burn it too.
I think I could just solder 5V to USB C or diod pad, but that is a much finer job.
Any ideas?

[ESP32-S3-Matrix-Sch.pdf](https://github.com/user-attachments/files/17019690/ESP32-S3-Matrix-Sch.pdf)

**Comment by dala318** [comment]
Have not tried, just using the USB-C port for now

**Comment by lufton** [comment]
Just be careful.
